GeziRehberi/Models/Places.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeziRehberi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Places
    {
        public int Id { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Address { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<decimal> AverageRating { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public string PhotoUrl { get; set; }
        public Nullable<byte> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Places Places1 { get; set; }
        public virtual Places Places2 { get; set; }
        public virtual Places Places11 { get; set; }
        public virtual Places Places3 { get; set; }
    }
}

GeziRehberi/Controllers/PlacesController.cs
using GeziRehberi.Helper;
using GeziRehberi.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace GeziRehberi.Controllers
{
    public class PlacesController : Controller
    {
        private GeziRehberiEntities db = new GeziRehberiEntities();

        [CustomAuthorize(Roles = "Admin,User")]
        public ActionResult List()
        {
            var places = db.Places.ToList();
            ViewBag.Cities = db.Cities.ToList();
            ViewBag.Categories = db.Categories.ToList();
            return View(places);
        }


        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Places place = db.Places.Find(id);
            if (place == null)
            {
                return HttpNotFound();
            }
            return View(place);
        }

        [CustomAuthorize(Roles = "Admin,User")]
        public ActionResult Create()
        {
            ViewBag.CityId = new SelectList(db.Cities, "Id", "Name");
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CityId,CategoryId,Name,Description,Address,Latitude,Longitude,AverageRating,ViewCount,PhotoUrl,IsActive,CreatedDate")] Places place, HttpPostedFileBase photoFile)
        {
            if (ModelState.IsValid)
            {
                place.CreatedDate = DateTime.Now;
                if (place.ViewCount == null)
                {
                    place.ViewCount = 0;
                }

                // Fotoğraf yükleme işlemi
                if (photoFile != null && photoFile.ContentLength > 0)
                {
                    string uploadPath = Server.MapPath("~/Uploads/Places/");
                    if (!Directory.Exists(uploadPath))
                    {
                        Directory.CreateDirectory(uploadPath);
                    }

                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(photoFile.FileName);
                    string filePath = Path.Combine(uploadPath, fileName);
                    photoFile.SaveAs(filePath);
                    place.PhotoUrl = "/Uploads/Places/" + fileName;
                }

                db.Places.Add(place);
                db.SaveChanges();
                return RedirectToAction("List");
            }
            ViewBag.CityId = new SelectList(db.Cities, "Id", "Name", place.CityId);
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", place.CategoryId);
            return View(place);
        }
        [CustomAuthorize(Roles = "Admin,User")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Places place = db.Places.Find(id);
            if (place == null)
            {
                return HttpNotFound();
            }
            ViewBag.CityId = new SelectList(db.Cities, "Id", "Name", place.CityId);
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", place.CategoryId);
            return View(place);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CityId,CategoryId,Name,Description,Address,Latitude,Longitude,AverageRating,ViewCount,PhotoUrl,IsActive,CreatedDate")] Places place, HttpPostedFileBase photoFile)
        {
            if (ModelState.IsValid)
            {
                // Fotoğraf yükleme işlemi
                if (photoFile != null && photoFile.ContentLength > 0)
                {
                    // Eski fotoğrafı sil
                    if (!string.IsNullOrEmpty(place.PhotoUrl))
                    {
                        string oldFilePath = Server.MapPath(place.PhotoUrl);
                        if (System.IO.File.Exists(oldFilePath))
                        {
                            System.IO.File.Delete(oldFilePath);
                        }
                    }

                    string uploadPath = Server.MapPath("~/Uploads/Places/");
                    if (!Directory.Exists(uploadPath))
                    {
                        Directory.CreateDirectory(uploadPath);
                    }

                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(photoFile.FileName);
                    string filePath = Path.Combine(uploadPath, fileName);
                    photoFile.SaveAs(filePath);
                    place.PhotoUrl = "/Uploads/Places/" + fileName;
                }

                db.Entry(place).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("List");
            }
            ViewBag.CityId = new SelectList(db.Cities, "Id", "Name", place.CityId);
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", place.CategoryId);
            return View(place);
        }

      
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            Places place = db.Places.Find(id);
            db.Places.Remove(place);
            db.SaveChanges();
            return RedirectToAction("List");
        }
    }
}

GeziRehberi/Views/Places/Create.cshtml
@model GeziRehberi.Models.Places

@{
    ViewBag.Title = "Yeni Mekan Ekle";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="content-wrapper">
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Yeni Yer Ekle</h4>


                    @using (Html.BeginForm("Create", "Places", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            <div class="form-group">
                                @Html.LabelFor(model => model.Name, "Adı", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.CityId, "Şehir", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownList("CityId", null, "-- Şehir Seçiniz --", htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.CityId, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.CategoryId, "Kategori", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownList("CategoryId", null, "-- Kategori Seçiniz --", htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Description, "Açıklama", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.Description, new { @class = "form-control", rows = "4" })
                                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Address, "Adres", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Latitude, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Latitude, new { htmlAttributes = new { @class = "form-control", type = "number", step = "0.000001" } })
                                    @Html.ValidationMessageFor(model => model.Latitude, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Longitude, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Longitude, new { htmlAttributes = new { @class = "form-control", type = "number", step = "0.000001" } })
                                    @Html.ValidationMessageFor(model => model.Longitude, "", new { @class = "text-danger" })
                                </div>
                            </div>


                            <div class="form-group">
                                @Html.LabelFor(model => model.PhotoUrl, "Fotoğraf", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    <input type="file" name="photoFile" id="photoFile" class="form-control" accept="image/*" />
                                    @Html.ValidationMessageFor(model => model.PhotoUrl, "", new { @class = "text-danger" })
                                    <small class="form-text text-muted">JPG veya PNG formatında fotoğraf yükleyebilirsiniz.</small>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Kaydet" class="btn btn-primary" />
                                    <a href="@Url.Action("List")" class="btn btn-secondary">İptal</a>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

GeziRehberi/Views/Places/Edit.cshtml
@model GeziRehberi.Models.Places

@{
    ViewBag.Title = "Mekan Düzenle";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="content-wrapper">
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Yer Düzenle</h4>
                  

                    @using (Html.BeginForm("Edit", "Places", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.Id)
                            @Html.HiddenFor(model => model.CreatedDate)

                            <div class="form-group">
                                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.CityId, "Şehir", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownList("CityId", null, "-- Şehir Seçiniz --", htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.CityId, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.CategoryId, "Kategori", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownList("CategoryId", null, "-- Kategori Seçiniz --", htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Description, "Açıklama", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.Description, new { @class = "form-control", rows = "4" })
                                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Address,"Adres", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Latitude, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Latitude, new { htmlAttributes = new { @class = "form-control", type = "number", step = "0.000001" } })
                                    @Html.ValidationMessageFor(model => model.Latitude, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Longitude, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Longitude, new { htmlAttributes = new { @class = "form-control", type = "number", step = "0.000001" } })
                                    @Html.ValidationMessageFor(model => model.Longitude, "", new { @class = "text-danger" })
                                </div>
                            </div>

                        
                            <div class="form-group">
                                @Html.LabelFor(model => model.PhotoUrl, "Fotoğraf", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @if (!string.IsNullOrEmpty(Model.PhotoUrl))
                                    {
                                        <div class="mb-2">
                                            <img src="@Model.PhotoUrl" alt="Mevcut Fotoğraf" style="max-width: 200px; max-height: 200px; border: 1px solid #ddd; padding: 5px;" />
                                            <br />
                                            <small class="text-muted">Mevcut Fotoğraf</small>
                                        </div>
                                    }
                                    <input type="file" name="photoFile" id="photoFile" class="form-control" accept="image/*" />
                                    @Html.HiddenFor(model => model.PhotoUrl)
                                    @Html.ValidationMessageFor(model => model.PhotoUrl, "", new { @class = "text-danger" })
                                    <small class="form-text text-muted">Yeni fotoğraf yüklemek için dosya seçin. Boş bırakırsanız mevcut fotoğraf korunur.</small>
                                </div>
                            </div>
                

                            <div class="form-group">
                                @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    <div class="checkbox">
                                        @Html.EditorFor(model => model.IsActive)
                                        @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Güncelle" class="btn btn-primary" />
                                    <a href="@Url.Action("List")" class="btn btn-secondary">İptal</a>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

GeziRehberi/Views/Places/List.cshtml
@model IEnumerable<GeziRehberi.Models.Places>

@{
    ViewBag.Title = "Mekanlar";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="content-wrapper">
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Yerler Listesi</h4>
                    <p class="card-description">
                        <a href="@Url.Action("Create","Places")" class="btn btn-primary btn-sm">
                            <i class="mdi mdi-plus"></i> Yeni Mekan Ekle
                        </a>
                    </p>
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Adı</th>
                                    <th>Şehir</th>
                                    <th>Kategori</th>
                                    <th>Adres</th>
                                    <th>Ortalama Puan</th>
                                    <th>Görüntülenme</th>
                                    <th>Aktif / Pasif</th>
                                    <th>Fotoğraf</th>
                                    <th>İşlemler</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>@item.Name</td>
                                        <td>
                                            @{
                                                string cityName = "-";
                                                if (ViewBag.Cities != null && item.CityId.HasValue)
                                                {
                                                    var cities = ViewBag.Cities as IEnumerable<dynamic>;
                                                    var city = cities?.FirstOrDefault(c => (int)c.Id == item.CityId.Value);
                                                    cityName = city?.Name ?? "-";
                                                }
                                            }
                                            @cityName
                                        </td>
                                        <td>
                                            @{
                                                string categoryName = "-";
                                                if (ViewBag.Categories != null && item.CategoryId.HasValue)
                                                {
                                                    var categories = ViewBag.Categories as IEnumerable<dynamic>;
                                                    var category = categories?.FirstOrDefault(c => (int)c.Id == item.CategoryId.Value);
                                                    categoryName = category?.Name ?? "-";
                                                }
                                            }
                                            @categoryName
                                        </td>
                                        <td>@(item.Address != null && item.Address.Length > 50 ? item.Address.Substring(0, 50) + "..." : item.Address ?? "-")</td>
                                        <td>@(item.AverageRating?.ToString("F1") ?? "-")</td>
                                        <td>@(item.ViewCount ?? 0)</td>
                                        <td>
                                            @if (item.IsActive == 1)
                                            {
                                                <span class="badge badge-success">Aktif</span>
                                            }
                                            else
                                            {
                                                <span class="badge badge-danger">Pasif</span>
                                            }
                                        </td>
                                        <td>
                                            <img src="@item.PhotoUrl" style="width:50px;height:50px;" />
                                        </td>
                                        <td>
                                            <a href="@Url.Action("Edit", new { id = item.Id })" class="btn btn-sm btn-success">
                                                <i class="mdi mdi-pencil"></i> Düzenle
                                            </a>
                                            @using (Html.BeginForm("Delete", "Places", new { id = item.Id }, FormMethod.Post, new { @class = "d-inline", onsubmit = "return confirm('Bu yeri silmek istediğinize emin misiniz?');" }))
                                            {
                                                @Html.AntiForgeryToken()
                                                <button type="submit" class="btn btn-sm btn-danger">
                                                    <i class="mdi mdi-delete"></i> Sil
                                                </button>
                                            }
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>