GeziRehberi/Controllers/CountriesController.cs
using GeziRehberi.Helper;
using GeziRehberi.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Diagnostics.Metrics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Windows.Forms;
namespace GeziRehberi.Controllers
{
    public class CountriesController : Controller
    {
      private GeziRehberiEntities db= new GeziRehberiEntities();
        [CustomAuthorize(Roles = "Admin")]
        public ActionResult List()
        {
            var countries = db.Countries.ToList();
            return View(countries);
        }
        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,CreatedDate,IsActive")] Countries country)
        {
            if (ModelState.IsValid)
            {
                country.CreatedDate = DateTime.Now;
                country.IsActive = true;             
                db.Countries.Add(country);
                db.SaveChanges();
                return RedirectToAction("List");
            }

            return View(country);
        }
        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Countries country = db.Countries.Find(id);
            if (country == null)
            {
                return HttpNotFound();
            }
            return View(country);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,CreatedDate,IsActive")] Countries country)
        {
            if (ModelState.IsValid)
            {
                db.Entry(country).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("List");
            }
            return View(country);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            Countries country = db.Countries.Find(id);
            db.Countries.Remove(country);
            db.SaveChanges();
            return RedirectToAction("List");
        }

 
    }
}

GeziRehberi/Views/Countries/Create.cshtml
@model GeziRehberi.Models.Countries
@{
    ViewBag.Title = "Yeni Ülke Ekle";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="content-wrapper">
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Yeni Ülke Ekle</h4>

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            <div class="form-group">
                                <label for="exampleInputUsername1">Adı</label>
                             
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Kaydet" formaction="Create" class="btn btn-primary" />
                                    <a href="@Url.Action("List")" class="btn btn-secondary">İptal</a>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

GeziRehberi/Views/Countries/Edit.cshtml
@model GeziRehberi.Models.Countries

@{
    ViewBag.Title = "Ülke Düzenle";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="content-wrapper">
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Ülke Düzenle</h4>
                   

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.Id)
                            @Html.HiddenFor(model => model.CreatedDate)

                            <div class="form-group">
                                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>

              
                            <div class="form-group">
                                @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    <div class="checkbox">
                                        @Html.EditorFor(model => model.IsActive)
                                        @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Güncelle" formaction="Edit" class="btn btn-primary" />
                                    <a href="@Url.Action("List")" class="btn btn-secondary">İptal</a>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

GeziRehberi/Views/Countries/List.cshtml
@model IEnumerable<GeziRehberi.Models.Countries>
@{
    ViewBag.Title = "Ülkeler";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}


<div class="content-wrapper">
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Ülkeler Listesi</h4>
                    <p class="card-description">
                        <a href="@Url.Action("Create","Countries")" class="btn btn-primary btn-sm">
                            <i class="mdi mdi-plus"></i> Yeni Ülke Ekle
                        </a>
                    </p>
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Adı</th>
                                    <th>Oluşturulma Tarihi</th>
                                    <th>Aktif / Pasif</th>
                                    <th>İşlemler</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>@item.Name</td>
                                        <td>@(item.CreatedDate?.ToString("dd.MM.yyyy") ?? "-")</td>
                                        <td>
                                            @if (item.IsActive == true)
                                            {
                                                <span class="badge badge-success">Aktif</span>
                                            }
                                            else
                                            {
                                                <span class="badge badge-danger">Pasif</span>
                                            }
                                        </td>
                                        <td>
                                            <a href="@Url.Action("Edit", new { id = item.Id })" class="btn btn-sm btn-success">
                                                <i class="mdi mdi-pencil"></i> Düzenle
                                            </a>
                                            @using (Html.BeginForm("Delete", "Countries", new { id = item.Id }, FormMethod.Post, new { @class = "d-inline", onsubmit = "return confirm('Bu ülkeyi silmek istediğinize emin misiniz?');" }))
                                            {
                                                @Html.AntiForgeryToken()
                                                <button type="submit" class="btn btn-sm btn-danger">
                                                    <i class="mdi mdi-delete"></i> Sil
                                                </button>
                                            }
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>