GeziRehberi/Models/BlogPhotos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeziRehberi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogPhotos
    {
        public int Id { get; set; }
        public Nullable<int> BlogId { get; set; }
        public string PhotoUrl { get; set; }
        public Nullable<bool> IsCover { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual BlogPhotos BlogPhotos1 { get; set; }
        public virtual BlogPhotos BlogPhotos2 { get; set; }
    }
}

GeziRehberi/Controllers/BlogPhotosController.cs
using GeziRehberi.Helper;
using GeziRehberi.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace GeziRehberi.Controllers
{
    public class BlogPhotosController : Controller
    {
        private GeziRehberiEntities db = new GeziRehberiEntities();
        List<Blogs> blogs;
        List<BlogPhotos> blogPhotos;

        [CustomAuthorize(Roles = "Admin,User")]
        public ActionResult List()
        {
            var userId = Convert.ToInt32(Session["UserId"]);
            var userRole = Session["Role"];
            if (userRole == "Admin")
            {
                blogPhotos = db.BlogPhotos.ToList();
            }
            else
            {
                blogPhotos =
                (from p in db.BlogPhotos
                 join b in db.Blogs on p.BlogId equals b.Id
                 where b.UserId == userId
                 select p)
                .ToList();
             
            }
       
            ViewBag.Blogs = db.Blogs.ToList();
            return View(blogPhotos);
        }

 
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPhotos blogPhoto = db.BlogPhotos.Find(id);
            if (blogPhoto == null)
            {
                return HttpNotFound();
            }
            return View(blogPhoto);
        }

        [CustomAuthorize(Roles = "Admin,User")]
        public ActionResult Create()
        {
            ViewBag.BlogId = new SelectList(db.Blogs, "Id", "Title");
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(int? BlogId, HttpPostedFileBase[] photoFiles, string[] isCover)
        {
            if (BlogId == null)
            {
                ModelState.AddModelError("BlogId", "Blog seçimi zorunludur.");
            }

            if (photoFiles == null || photoFiles.Length == 0 || photoFiles.All(f => f == null))
            {
                ModelState.AddModelError("", "En az bir fotoğraf seçmelisiniz.");
            }

            if (ModelState.IsValid)
            {
                string uploadPath = Server.MapPath("~/Uploads/BlogPhotos/");
                if (!Directory.Exists(uploadPath))
                {
                    Directory.CreateDirectory(uploadPath);
                }

                int photoIndex = 0;
                for (int i = 0; i < photoFiles.Length; i++)
                {
                    if (photoFiles[i] != null && photoFiles[i].ContentLength > 0)
                    {
                        string fileName = Guid.NewGuid().ToString() + Path.GetExtension(photoFiles[i].FileName);
                        string filePath = Path.Combine(uploadPath, fileName);
                        photoFiles[i].SaveAs(filePath);

                        // Kapak fotoğrafı kontrolü - checkbox index'ine göre
                        bool isCoverPhoto = isCover != null && isCover.Contains(photoIndex.ToString());

                        BlogPhotos blogPhoto = new BlogPhotos
                        {
                            BlogId = BlogId,
                            PhotoUrl = "/Uploads/BlogPhotos/" + fileName,
                            IsCover = isCoverPhoto,
                            CreatedDate = DateTime.Now,
                            IsActive = true
                        };

                        db.BlogPhotos.Add(blogPhoto);
                        photoIndex++;
                    }
                }

                db.SaveChanges();
                return RedirectToAction("List");
            }

            ViewBag.BlogId = new SelectList(db.Blogs, "Id", "Title", BlogId);
            return View();
        }

        // GET: BlogPhotos/Edit/5
        [CustomAuthorize(Roles = "Admin,User")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BlogPhotos blogPhoto = db.BlogPhotos.Find(id);
            if (blogPhoto == null)
            {
                return HttpNotFound();
            }
            ViewBag.BlogId = new SelectList(db.Blogs, "Id", "Title", blogPhoto.BlogId);
            return View(blogPhoto);
        }

        // POST: BlogPhotos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,BlogId,PhotoUrl,IsCover,CreatedDate,IsActive")] BlogPhotos blogPhoto, HttpPostedFileBase photoFile)
        {
            if (ModelState.IsValid)
            {
                // Yeni fotoğraf yükleme işlemi
                if (photoFile != null && photoFile.ContentLength > 0)
                {
                    // Eski fotoğrafı sil
                    if (!string.IsNullOrEmpty(blogPhoto.PhotoUrl))
                    {
                        string oldFilePath = Server.MapPath(blogPhoto.PhotoUrl);
                        if (System.IO.File.Exists(oldFilePath))
                        {
                            System.IO.File.Delete(oldFilePath);
                        }
                    }

                    string uploadPath = Server.MapPath("~/Uploads/BlogPhotos/");
                    if (!Directory.Exists(uploadPath))
                    {
                        Directory.CreateDirectory(uploadPath);
                    }

                    string fileName = Guid.NewGuid().ToString() + Path.GetExtension(photoFile.FileName);
                    string filePath = Path.Combine(uploadPath, fileName);
                    photoFile.SaveAs(filePath);
                    blogPhoto.PhotoUrl = "/Uploads/BlogPhotos/" + fileName;
                }

                db.Entry(blogPhoto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("List");
            }
            ViewBag.BlogId = new SelectList(db.Blogs, "Id", "Title", blogPhoto.BlogId);
            return View(blogPhoto);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        [CustomAuthorize(Roles = "Admin,User")]
        public ActionResult Delete(int id)
        {
            BlogPhotos blogPhoto = db.BlogPhotos.Find(id);

            // Fotoğrafı sil
            if (!string.IsNullOrEmpty(blogPhoto.PhotoUrl))
            {
                string filePath = Server.MapPath(blogPhoto.PhotoUrl);
                if (System.IO.File.Exists(filePath))
                {
                    System.IO.File.Delete(filePath);
                }
            }

            db.BlogPhotos.Remove(blogPhoto);
            db.SaveChanges();
            return RedirectToAction("List");
        }

    }
}

GeziRehberi/Views/BlogPhotos/Create.cshtml
@{
    ViewBag.Title = "Yeni Blog Fotoğrafı Ekle";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="content-wrapper">
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Yeni Blog Fotoğrafı Ekle</h4>
                   
                    @using (Html.BeginForm("Create", "BlogPhotos", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            <div class="form-group">
                                <label class="control-label col-md-2">Blog</label>
                                <div class="col-md-10">
                                    @Html.DropDownList("BlogId", null, "-- Blog Seçiniz --", htmlAttributes: new { @class = "form-control", required = "required" })
                                    <span class="field-validation-valid text-danger" data-valmsg-for="BlogId" data-valmsg-replace="true"></span>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-2">Fotoğraflar</label>
                                <div class="col-md-10">
                                    <input type="file" name="photoFiles" id="photoFiles" class="form-control" accept="image/*" multiple required />
                                    <small class="form-text text-muted">Birden fazla fotoğraf seçebilirsiniz. JPG veya PNG  formatında fotoğraf yükleyebilirsiniz.</small>
                                    <div id="photoPreview" class="mt-3"></div>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label col-md-2">Kapak Fotoğrafı</label>
                                <div class="col-md-10">
                                    <div id="coverCheckboxes"></div>
                                    <small class="form-text text-muted">Kapak fotoğrafı olarak işaretlemek istediğiniz fotoğrafı seçin.</small>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Kaydet" class="btn btn-primary" />
                                    <a href="@Url.Action("List")" class="btn btn-secondary">İptal</a>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('#photoFiles').on('change', function () {
                var files = this.files;
                var preview = $('#photoPreview');
                var checkboxes = $('#coverCheckboxes');
                preview.html('');
                checkboxes.html('');

                if (files.length > 0) {
                    var photoIndex = 0;
                    for (var i = 0; i < files.length; i++) {
                        var file = files[i];
                        if (file && file.type.startsWith('image/')) {
                            var reader = new FileReader();
                            var currentIndex = photoIndex;

                            reader.onload = (function (idx) {
                                return function (e) {
                                    var div = $('<div class="mb-2 d-inline-block mr-3" style="position: relative;">');
                                    div.append('<img src="' + e.target.result + '" style="max-width: 150px; max-height: 150px; border: 1px solid #ddd; padding: 5px;" />');
                                    preview.append(div);

                                    var checkboxDiv = $('<div class="form-check mb-2">');
                                    checkboxDiv.append('<input type="checkbox" name="isCover" value="' + idx + '" id="isCover_' + idx + '" class="form-check-input" />');
                                    checkboxDiv.append('<label class="form-check-label" for="isCover_' + idx + '">Kapak Fotoğrafı</label>');
                                    checkboxes.append(checkboxDiv);
                                };
                            })(currentIndex);

                            reader.readAsDataURL(file);
                            photoIndex++;
                        }
                    }
                }
            });
        });
    </script>
}

GeziRehberi/Views/BlogPhotos/Edit.cshtml
@model GeziRehberi.Models.BlogPhotos

@{
    ViewBag.Title = "Blog Fotoğrafı Düzenle";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="content-wrapper">
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Blog Fotoğrafı Düzenle</h4>
                   

                    @using (Html.BeginForm("Edit", "BlogPhotos", FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            @Html.HiddenFor(model => model.Id)
                            @Html.HiddenFor(model => model.CreatedDate)

                            <div class="form-group">
                                @Html.LabelFor(model => model.BlogId, "Blog", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownList("BlogId", null, "-- Blog Seçiniz --", htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.BlogId, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.PhotoUrl, "Fotoğraf", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @if (!string.IsNullOrEmpty(Model.PhotoUrl))
                                    {
                                        <div class="mb-2">
                                            <img src="@Model.PhotoUrl" alt="Mevcut Fotoğraf" style="max-width: 200px; max-height: 200px; border: 1px solid #ddd; padding: 5px;" />
                                            <br />
                                            <small class="text-muted">Mevcut Fotoğraf</small>
                                        </div>
                                    }
                                    <input type="file" name="photoFile" id="photoFile" class="form-control" accept="image/*" />
                                    @Html.HiddenFor(model => model.PhotoUrl)
                                    @Html.ValidationMessageFor(model => model.PhotoUrl, "", new { @class = "text-danger" })
                                    <small class="form-text text-muted">Yeni fotoğraf yüklemek için dosya seçin. Boş bırakırsanız mevcut fotoğraf korunur.</small>
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.IsCover, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    <div class="checkbox">
                                        @Html.EditorFor(model => model.IsCover)
                                        @Html.ValidationMessageFor(model => model.IsCover, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    <div class="checkbox">
                                        @Html.EditorFor(model => model.IsActive)
                                        @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Güncelle" class="btn btn-primary" />
                                    <a href="@Url.Action("List")" class="btn btn-secondary">İptal</a>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>

GeziRehberi/Views/BlogPhotos/List.cshtml
@model IEnumerable<GeziRehberi.Models.BlogPhotos>

@{
    ViewBag.Title = "Blog Fotoğrafları";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="content-wrapper">
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Blog Fotoğrafları Listesi</h4>
                    <p class="card-description">
                        <a href="@Url.Action("Create","BlogPhotos")" class="btn btn-primary btn-sm">
                            <i class="mdi mdi-plus"></i> Yeni Fotoğraf Ekle
                        </a>
                    </p>
                    <div class="table-responsive">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Blog</th>
                                    <th>Fotoğraf</th>
                                    <th>Kapak Fotoğrafı</th>
                                    <th>Oluşturulma Tarihi</th>
                                    <th>Aktif / Pasif</th>
                                    <th>İşlemler</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>
                                            @{
                                                string blogTitle = "-";
                                                if (ViewBag.Blogs != null && item.BlogId.HasValue)
                                                {
                                                    var blogs = ViewBag.Blogs as IEnumerable<dynamic>;
                                                    var blog = blogs?.FirstOrDefault(b => (int)b.Id == item.BlogId.Value);
                                                    blogTitle = blog?.Title ?? "-";
                                                }
                                            }
                                            @blogTitle
                                        </td>
                                        <td>
                                            @if (!string.IsNullOrEmpty(item.PhotoUrl))
                                            {
                                                <img src="@item.PhotoUrl" alt="Fotoğraf" style="max-width: 100px; max-height: 100px; border: 1px solid #ddd; padding: 5px;" />
                                            }
                                            else
                                            {
                                                <span>-</span>
                                            }
                                        </td>
                                        <td>
                                            @if (item.IsCover == true)
                                            {
                                                <span class="badge badge-success">Evet</span>
                                            }
                                            else
                                            {
                                                <span class="badge badge-secondary">Hayır</span>
                                            }
                                        </td>
                                        <td>@(item.CreatedDate?.ToString("dd.MM.yyyy") ?? "-")</td>
                                        <td>
                                            @if (item.IsActive == true)
                                            {
                                                <span class="badge badge-success">Aktif</span>
                                            }
                                            else
                                            {
                                                <span class="badge badge-danger">Pasif</span>
                                            }
                                        </td>
                                        <td>
                                            <a href="@Url.Action("Edit", new { id = item.Id })" class="btn btn-sm btn-warning">
                                                <i class="mdi mdi-pencil"></i> Düzenle
                                            </a>
                                            @using (Html.BeginForm("Delete", "BlogPhotos", new { id = item.Id }, FormMethod.Post, new { @class = "d-inline", onsubmit = "return confirm('Bu fotoğrafı silmek istediğinize emin misiniz?');" }))
                                            {
                                                @Html.AntiForgeryToken()
                                                <button type="submit" class="btn btn-sm btn-danger">
                                                    <i class="mdi mdi-delete"></i> Sil
                                                </button>
                                            }
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>